#!/usr/bin/env python3
"""Generate the trap handler table from TRAP(Name) definitions in src/os."""
import re, sys, glob, os

out = sys.argv[1]
srcs = sys.argv[2:]
names = []
for f in srcs:
    for m in re.finditer(r'^TRAP\((\w+)\)', open(f).read(), re.M):
        names.append(m.group(1))
dups = {n for n in names if names.count(n) > 1}
if dups:
    sys.exit('duplicate TRAP definitions: ' + ', '.join(sorted(dups)))
names.sort()
text = '/* generated by tools/gen_traps.py */\n#include "../../src/os/os.h"\n'
text += ''.join(f'void trap_{n}(CPU *);\n' for n in names)
text += 'const TrapDef g_trap_defs[] = {\n'
text += ''.join(f'    {{"{n}", trap_{n}}},\n' for n in names)
text += '    {0, 0}\n};\nconst int g_trap_ndefs = %d;\n' % len(names)
os.makedirs(os.path.dirname(out), exist_ok=True)
if not os.path.exists(out) or open(out).read() != text:
    open(out, 'w').write(text)
