#!/usr/bin/env python3
"""Embed font files as C arrays: gen_fonts.py OUT.c NAME=FILE..."""
import sys, os

out = sys.argv[1]
text = '/* generated by tools/gen_fonts.py */\n'
for arg in sys.argv[2:]:
    name, path = arg.split('=', 1)
    data = open(path, 'rb').read()
    text += f'/* {os.path.basename(path)} */\nconst unsigned char {name}[{len(data)}] = {{\n'
    for i in range(0, len(data), 24):
        text += ','.join(str(b) for b in data[i:i + 24]) + ',\n'
    text += f'}};\nconst unsigned int {name}_len = {len(data)};\n'
os.makedirs(os.path.dirname(out), exist_ok=True)
if not os.path.exists(out) or open(out).read() != text:
    open(out, 'w').write(text)
